### ISSUE TITLE
Hanken To-Do list for publishing into GF

### ISSUE THREAD

**Issue by vv-monsalve** [marcologous/hanken-grotesk#66]
Hi @marcologous,

This would be the To-Do list resuming what would be remaining for the publishing process to GF

- [x] Review/solve the reported issue on [mathematical signs](https://github.com/marcologous/hanken-grotesk/issues/56)
- [x] Review [Vietnamese stacked diacritics](https://github.com/marcologous/hanken-grotesk/issues/63)
- [x] Adjust [bracket layers](https://github.com/marcologous/hanken-grotesk/issues/62#issuecomment-740211502) for composite glyphs
- [x] Review the [Outline Quality Checklist](https://github.com/marcologous/hanken-grotesk/issues/61) and ensure everything is ok for Hanken Grotesk
- [x] Review/edit the information files (Description, Authors, Contributors)

Fontbakery has improved a lot and is now on version 0.7.34, I tested the current fonts in my local folder and there are two new reported Fails that we should take care of. Nevertheless, it would be better to cover the above first and work on the new source files.

I saw there is an [open PR](https://github.com/marcologous/hanken-grotesk/pull/65) that hasn't been merged, perhaps it covers some of the items on the list.

**Comment by marcologous** [comment]
Hi @vv-monsalve  I have been getting some errors on the diagnostic. I am not quite sure what the problem is. Would you be able to advise?

**Comment by vv-monsalve** [comment]
> Hi @vv-monsalve I have been getting some errors on the diagnostic. I am not quite sure what the problem is. Would you be able to advise?

If you are referring to the Travis CI, please ignore it and merge the pull request into the master so that I can pull them and resume the QA process for publishing. I'll test them locally.

It seems that Travis couldn't build the fonts to test it, but in any case, we are migrating from Travis to GitHub Actions for CI, so I think we should deprecate Travis in this repo anyway.

**Comment by vv-monsalve** [comment]
Hi @marcologous,  I've pulled the latest files at commit 0daaa1297210d26e4f4466ba4bf42cbaf7c20aaf but I received an error when trying to produce new font files.

After inspecting the source files I see now there is a new Regular master but, the Weight value for all the masters & instances version is now 100 in the Roman and 0 for the Italics, which is not right as each master and instance require a unique value.

Could you please inspect it and restore or assign the values?

![Hanken-Italic](https://user-images.githubusercontent.com/48698976/112220054-d01ff080-8bf3-11eb-8e2b-e56c3debfde4.gif)
![Hanken-Roman](https://user-images.githubusercontent.com/48698976/112220059-d1e9b400-8bf3-11eb-9801-6b200fd00aff.gif)

**Comment by vv-monsalve** [comment]
Hi @marcologous, how are you coming with the project? Please, let me know if you have any doubt.

**Comment by marcologous** [comment]
Hi @vv-monsalve ! I have merged the latest pull request with the main. Have the chance to have a look at it?

**Comment by vv-monsalve** [comment]
> Hi @vv-monsalve ! I have merged the latest pull request with the main. Have the chance to have a look at it?

Hi Alfredo. Thanks. I'm adding it to my queue now and I'll let you know as soon as I've run a QA round.

**Comment by vv-monsalve** [comment]
> Hi @vv-monsalve ! I have merged the latest pull request with the main. Have the chance to have a look at it?

Hi Alfredo. I've pulled the latest file in the repo, performed some adjustments and created a new PR with some notes on it.
Please give it a look and let me know if you have any questions.

Best

**Comment by vv-monsalve** [comment]
The topics listed in this issue have been covered. Closing this here.
